# 🐼 Pandas - Class 2: DataFrame Basics
Welcome to **Class 2**. Today we’ll learn how to **inspect**, **select**, and **organize** data inside a DataFrame.

## 1 Inspecting Data
Quick ways to understand your dataset:
- `head(n)` → first *n* rows (default 5)
- `tail(n)` → last *n* rows
- `info()` → columns, non-null counts, and dtypes
- `shape` → (rows, columns)
- `dtypes` → data type of each column

In [ ]:
import pandas as pd

# Create a small DataFrame
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [ ]:
b.head()
# it will show top 5 rows of the dataframe if ()leave empty otherwise the no.of provided rows
b.head(2)

    Name  Age  Score
0  Alice   25     88
1    Bob   30     92

In [ ]:
b.tail()
# it will show last 5 rows of the dataframe if ()leave empty otherwise the no.of provided rows
b.tail(2)

    Name  Age  Score
3  David   40     85
4   Emma   22     95

In [ ]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [ ]:
b.shape

(5, 3)

In [ ]:
b.dtypes

Name     object
Age       int64
Score     int64
dtype: object

In [ ]:
b.describe()

             Age      Score
count   5.000000   5.000000
mean   30.400000  87.800000
std     7.300685   6.220932
min    22.000000  79.000000
25%    25.000000  85.000000
50%    30.000000  88.000000
75%    35.000000  92.000000
max    40.000000  95.000000

## 2 Selecting Columns & Rows
Ways to access parts of a DataFrame:
- Single column → `df['col']`
- Multiple columns → `df[['col1','col2']]`
- Label-based selection → `df.loc[row_label, col_label]`
- Integer-index selection → `df.iloc[row_idx, col_idx]`
Tip: `:` means "all rows/columns" in that dimension.

In [ ]:
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [ ]:
b['Name']

0      Alice
1        Bob
2    Charlie
3      David
4       Emma
Name: Name, dtype: object

In [ ]:
b[['Name','Score']]

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     79
3    David     85
4     Emma     95

In [ ]:
b.loc[0]
#loc[lable]
# work same a indexing and select a row index and sho it in column form

Name     Alice
Age         25
Score       88
Name: 0, dtype: object

In [ ]:
b.loc[[1,2,3],["Name","Age"]]

      Name  Age
1      Bob   30
2  Charlie   35
3    David   40

## 3 Index & Columns Overview
- `df.index` → row labels
- `df.columns` → column names
- `df.values` → underlying NumPy array (read-only; prefer using DataFrame ops)

In [ ]:
b.index
# it give the range of index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
b.columns
# it will provide all the columns present in dataframe

Index(['Name', 'Age', 'Score'], dtype='object')

In [ ]:
b.values
# it will create a 2D array

array([['Alice', 25, 88],
       ['Bob', 30, 92],
       ['Charlie', 35, 79],
       ['David', 40, 85],
       ['Emma', 22, 95]], dtype=object)

## 4 Renaming Columns & Setting an Index
- Rename columns → `df.rename(columns={'old':'new'}, inplace=False)`
- Set a column as index → `df.set_index('column_name', inplace=False)`
- Reset index → `df.reset_index(inplace=False)`
 If you don't use `inplace=True`, remember to assign the result back to a variable.

In [ ]:
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [ ]:
b.rename(columns={"Score":"Marks"},inplace=True)
# {oldname:newname}(you can pass multiple columns), inplace permanently save the change in the main dataframes
b=b.rename(columns={"Score":"Marks"})
# second method is name as first different method
b

      Name  Age  Marks
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [ ]:
b.set_index("Name")
# it will change the label
# use inplace=True to save it permanently

         Age  Marks
Name
Alice     25     88
Bob       30     92
Charlie   35     79
David     40     85
Emma      22     95

In [ ]:
b.iloc[0]
# if you use set_index and change indexes but you want to access df with normal labels (0,1,2)

Name     Alice
Age         25
Marks       88
Name: 0, dtype: object

In [ ]:
b.reset_index()
#b.reset_index(inplace=True)
# you canonly run it 2 times only it will make labe(0,1,2,3) as a new column

## 5 Basic Attributes Recap
- `df.columns` → names of all columns
- `df.index` → row labels
- `df.values` → NumPy array (data only)
These are handy for quick checks and loops (though vectorized ops are preferred).

## Mini Practice
1. Create a DataFrame with at least 5 rows and 4 columns (mix of numeric + text).
2. Show the first 3 rows, last 2 rows, and the info.
3. Select a sub-DataFrame with only 2 columns.
4. Rename one column and set any column as index, then reset it back.
5. Print `df.shape`, `df.dtypes`, and `df.columns`.

In [2]:
import pandas as pd

# Create a DataFrame with at least 5 rows & 4 columns (mix of numbers + text)
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)

# Show the first 3 rows, last 2 rows, and info
# your code here

# Select a sub-DataFrame with only 2 columns
# your code here

# Rename one column and set any column as index, then reset it back
# your code here

# Print df.shape, df.dtypes, and df.columns
# your code here

In [3]:
df.head(3)

      Name  Age    City  Score
0    Alice   25   Delhi     85
1      Bob   30  Mumbai     91
2  Charlie   35    Pune     78

In [4]:
df.tail(2)

    Name  Age       City  Score
3  David   40  Bangalore     88
4   Emma   22    Chennai     95

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Score   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [6]:
df[["Name","City"]]

      Name       City
0    Alice      Delhi
1      Bob     Mumbai
2  Charlie       Pune
3    David  Bangalore
4     Emma    Chennai

---
## ✅ Summary
- You learned to **inspect** a DataFrame (`head`, `tail`, `info`, `shape`, `dtypes`).
- You practiced **selecting** columns/rows using `[]`, `.loc`, and `.iloc`.
- You explored **index/columns** and basic attributes.
- You **renamed** columns and **set/reset** an index.

Next up: **Data Cleaning Essentials** (missing values, types, duplicates).